trigger:
- manual    

stages:
- stage: IaC_TF
  displayName: Terraform Infrastructure
  jobs:
  - job: Terraform     
    displayName: Terraform Deployment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: 'Terraform init'
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        backendServiceArm: 'AzLogin_because_i_dumb'
        backendAzureRmResourceGroupName: 'NSSFMsRG-smooth-sloth'
        backendAzureRmStorageAccountName: 'nssfmstorage'
        backendAzureRmContainerName: 'tf-state'
        backendAzureRmKey: 'tf/terraform.tfstate'
      displayName: 'Terraform init'    #if u need persistance better use S3 storage for tfstate files

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        environmentServiceNameAzureRM: 'AzLogin_because_i_dumb'
        commandOptions: '-out main.tfplan'
      displayName: 'Terraform plan'    

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        environmentServiceNameAzureRM: 'AzLogin_because_i_dumb'
        commandOptions: 'main.tfplan'
      displayName: 'Terraform apply'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/IaC/'
        artifact: 'backendConfiguration'
        publishLocation: 'pipeline'
      displayName: 'Publish Backend Configuration'

  - job: ApplyBackendConfiguration
    displayName: 'Apply Backend Configuration'
    pool:
      vmImage: ubuntu-latest
    dependsOn: Terraform
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'backendConfiguration'
        path: '$(System.DefaultWorkingDirectory)/backendConfiguration'
      displayName: 'Download Backend Configuration'

    - script: |
        cp -r $(System.DefaultWorkingDirectory)/backendConfiguration/* $(System.DefaultWorkingDirectory)/IaC/
        terraform init
        terraform apply -auto-approve
      displayName: 'Apply Backend Configuration'
      
    


   


