trigger:
- main
pr:
- '*'
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Set up Python'
  - script: |
      cd src
      npm install
      npm test
    displayName: 'Build and Test Node.js Application'
  - task: Docker@2
    inputs:
      command: 'build'
      arguments: '-t nssfmdemo:latest'
      Dockerfile: 'Dockerfile'
    displayName: 'Build Docker Image'
  - script: |
      image_id=$(docker images -q)
      echo "##vso[task.setvariable variable=image_id]$image_id"
    displayName: 'Set Docker Image ID'

  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubeconfig: $(kubeconfig)
      namespace: 'njsdemo'
      manifests: |
        Manifests/deployment.yml
        Manifests/service.yml
    displayName: 'Deploy to Kubernetes'




