trigger: 
- manual

stages:
- stage: deploy
  jobs:
  - job: deploy_ingress
    steps:
    - task: UseKubectl@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'nssfmK8s'
        command: 'apply'
        arguments: '-f nssfm-demo-ingress.yaml'
        displayName: 'Apply ingress configuration'

  
