trigger: 
- manual

stages:
- stage: deploy
  jobs:
  - job: deploy_ingress
    steps:
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'nssfmK8s'
        namespace: 'default'
        manifests: |
          Manifests/serviceLoadBalancer.yml
      displayName: 'Deploy to Kubernetes'

