trigger:
- main

stages:
- stage: Plan
  displayName: 'Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzLogin_because_i_dumb'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account show'
      displayName: 'Azure Login'
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: 'Install Terraform'
    - script: |
        cd $(System.DefaultWorkingDirectory)/IaC/
        terraform fmt -check -recursive -diff
      displayName: 'Check Terraform Formatting'
    - script: |
        cd $(System.DefaultWorkingDirectory)/IaC/
        terraform init
      displayName: 'Terraform Init'
    - script: |
        cd $(System.DefaultWorkingDirectory)/IaC/
        terraform validate
      displayName: 'Terraform Validate'
    - script: |
        cd $(System.DefaultWorkingDirectory)/IaC/
        terraform plan -out main.tfplan
      displayName: 'Terraform Plan (Save Plan)'
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'tf-plan-artifact'
        targetPath: '$(System.DefaultWorkingDirectory)/IaC/'
        publishLocation: 'pipeline'
      displayName: 'Publish Terraform Plan Artifact'

- stage: Apply
  displayName: 'Apply (with manual approve)'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzLogin_because_i_dumb'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account show'
      displayName: 'Azure Login'
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: 'Install Terraform'
    - script: |
        cd $(System.DefaultWorkingDirectory)/IaC/
        terraform init
      displayName: 'Terraform Init'
    - script: |
        cd $(System.DefaultWorkingDirectory)/IaC/
        terraform apply main.tfplan
      displayName: 'Terraform Apply'
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'kubeconfig-artifact'
        targetPath: '$(System.DefaultWorkingDirectory)/IaC/'
        publishLocation: 'pipeline'
      displayName: 'Publish kubeconfig Artifact'


