trigger:
- main
pr:
- '*'
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Set up Python'
  - script: |
      cd src
      npm install
      npm test
    displayName: 'Build and Test Node.js Application'
  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: 'Dockerfile'
    displayName: 'Build Docker Image'
    outputs:
      imageId: 'image_id'
  - task: Docker@2
    inputs:
      containerRegistry: 'nssfmdemo'
      repository: 'nssfmdemo'
      command: 'tag'
      imageId: $(image_id)
      tags: |
        $(Build.BuildId)
        nssfm/nssfmdemo:try
    displayName: 'Tag Docker Image'
  - task: Docker@2
    inputs:
      containerRegistry: 'nssfmdemo'
      repository: 'nssfmdemo'
      command: 'push'
      imageId: $(image_id)
      tags: |
        $(Build.BuildId)
        nssfm/nssfmdemo:try
    displayName: 'Push Docker Image to Registry'
  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      namespace: 'njsdemo'
      manifests: |
        Manifests/deployment.yml
        Manifests/service.yml
    displayName: 'Deploy to Kubernetes'



