trigger:
- manual

stages:
- stage: Backend_TFState
  displayName: 'Backend TFState'
  jobs:
  - job: Backend
    displayName: 'Upload TFState to Storage'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzLogin_because_i_dumb'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage blob upload \
            --account-name nssfmstorage \
            --account-key $(StorageAccountKey) \
            --container-name tf-state \
            --name terraform.tfstate \
            --type block \
            --content $(Build.SourcesDirectory)/IaC/terraform.tfstate



