trigger:
- none 

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: GetKubeconfigAndView
  displayName: 'Get Kubeconfig and View'
  steps:
  - script: |
      az aks get-credentials --resource-group NSSFMsRG-smooth-sloth --name cluster-current-ladybird
      kubectl config view
    displayName: 'Azure CLI - Get Kubeconfig and View'

