trigger:
- main

pr:
- '*'

stages:
- stage: IaC_TF
  displayName: Terraform Infrastructure
  jobs:
  - job: Terraform
    displayName: Terraform Deployment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        backendServiceArm: 'AzureRM-sp-Jan-M'
        backendAzureRmResourceGroupName: 'NSSFMsRG-smooth-sloth'
        backendAzureRmStorageAccountName: 'nssfmstorage'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'tfstate/terraform.tfstate'
      displayName: 'Terraform init'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        environmentServiceNameAzureRM: 'AzureRM-sp-Jan-M'
        commandOptions: '-out main.tfplan'
      displayName: 'Terraform plan'

    # Uncomment the following lines if you want to apply Terraform changes
    - task: TerraformTaskV4@4
      inputs:
         provider: 'azurerm'
         command: 'apply'
         workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
         environmentServiceNameAzureRM: 'AzureRM-sp-Jan-M'
         commandOptions: 'main.tfplan'
      displayName: 'Terraform apply'

    # Uncomment if want to destroy
    # - task: TerraformTaskV4@4
    #   inputs:
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
    #     provider: 'azurerm'
    #     command: 'destroy'
    #     environmentServiceNameAzureRM: 'AzureRM-sp-Jan-M'
    #   displayName: 'Terraform destroy'


