trigger: 
- manual

stages:
- stage: deploy
  jobs:
  - job: install_nginx_ingress_controller
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set up Python'

    - task: Kubernetes@1
      inputs:
        kubernetesServiceConnection: 'nssfmK8s'
        command: 'apply'
        arguments: '-f nssfm-demo-ingress2.yaml'
      displayName: 'Install NGINX Ingress Controller'

    - script: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
      displayName: 'Add NGINX Ingress Helm repository'

    - script: |
        kubectl create namespace nginx-ingress
        helm install nginx-ingress ingress-nginx/ingress-nginx --namespace nginx-ingress
      displayName: 'Install NGINX Ingress Controller'
