trigger:
- manual

stages:
- stage: deploy
  jobs:
  - job: install_helm_and_nginx_ingress
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set up Python'

    - script: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
      displayName: 'Install Helm'

    - script: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install nginx-ingress ingress-nginx/ingress-nginx
      displayName: 'Install NGINX Ingress Controller'

  - job: deploy_ingress
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'nssfmK8s'
        command: 'apply'
        arguments: '-f nssfm-demo-ingress2.yaml'
        displayName: 'Apply ingress configuration'
