trigger:
- manual

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Set up Python'
  
  - script: |
      cd src
      npm install
      npm test
    displayName: 'Build and Test Node.js Application'

  - task: Docker@2
    inputs:
      command: 'build'
      arguments: '-t nssfmdemo:latest'
      Dockerfile: 'Dockerfile'
    displayName: 'Build Docker Image'

  - script: |
      image_id=$(docker images -q)
      echo "image_id=$image_id" >> $(Agent.TempDirectory)/dockerimageid.txt
    displayName: 'Set Docker Image ID'

  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'nssfmK8s'
      namespace: 'default'
      manifests: |
        Manifests/deployment.yml
        Manifests/service.yml
    displayName: 'Deploy to Kubernetes'
    
   #For first instace use  Manifests/deployment.yml & Manifests/service.yml
   #For second instance use  Manifests/deploymentTheSecond.yml  Manifests/serviceTheSecond.yml
   #Better to use helmcharts for more compicated deployment and better splitting variables for dev/stage/prod env


 








