trigger: 
- manual

stages:
- stage: deploy
  jobs:
  - job: deploy_ingress
    steps:
    - task: Kubernetes@1
      inputs:
        kubectlServiceConnection: 'nssfmK8s'
        script: |
          kubectl apply -f nssfm-demo-ingress.yaml
        displayName: 'Apply ingress configuration'


  
