trigger:
- manual

stages:
- stage: IaC_TF
  displayName: Terraform Infrastructure
  jobs:
  - job: Terraform
    displayName: Terraform Deployment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
      displayName: 'Terraform init'
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        backendServiceArm: 'AzLogin_because_i_dumb'
        backendAzureRmResourceGroupName: 'NSSFMsRG-smooth-sloth'
        backendAzureRmStorageAccountName: 'nssfmstorage'
        backendAzureRmContainerName: 'tf-state'
        backendAzureRmKey: 'tf/terraform.tfstate'
      displayName: 'Terraform init'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        environmentServiceNameAzureRM: 'AzLogin_because_i_dumb'
        commandOptions: '-out main.tfplan'
      displayName: 'Terraform plan'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        environmentServiceNameAzureRM: 'AzLogin_because_i_dumb'
        commandOptions: 'main.tfplan'
      displayName: 'Terraform apply'

    - script: |
        cluster_url=$(terraform output kubernetes_cluster_url)
        ca_cert_data=$(terraform output kubernetes_ca_cert_data)
        client_cert_data=$(terraform output kubernetes_client_cert_data)
        client_key_data=$(terraform output kubernetes_client_key_data)

        mkdir -p $(System.DefaultWorkingDirectory)/IaC/.kube
        echo "$cluster_url" | base64 -d > $(System.DefaultWorkingDirectory)/IaC/.kube/config
        echo "$ca_cert_data" | base64 -d >> $(System.DefaultWorkingDirectory)/IaC/.kube/config
        echo "$client_cert_data" | base64 -d >> $(System.DefaultWorkingDirectory)/IaC/.kube/config
        echo "$client_key_data" | base64 -d >> $(System.DefaultWorkingDirectory)/IaC/.kube/config

        az pipelines variable create --name KUBECONFIG --value "$(cat $(System.DefaultWorkingDirectory)/IaC/.kube/config)" --org https://dev.azure.com/BTT-Candidates/ --project "Jan M Project"
      displayName: 'Create and set Kubernetes config'





    #- task: TerraformTaskV4@4
    #  inputs:
    #    workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
    #    provider: 'azurerm'
    #    command: 'destroy'
    #    environmentServiceNameAzureRM: 'AzLogin_because_i_dumb'

   


