trigger:
- main

stages:
- stage: IaC_TF
  displayName: Terraform Infrastructure
  jobs:
  - job: Terraform
    displayName: Terraform Deployment
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        backendServiceArm: 'AzLogin_because_i_dumb'
        backendAzureRmResourceGroupName: 'NSSFMsRG-smooth-sloth'
        backendAzureRmStorageAccountName: 'nssfmstorage'
        backendAzureRmContainerName: 'tf-state'
        backendAzureRmKey: 'tf/terraform.tfstate'
      displayName: 'Terraform init'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        environmentServiceNameAzureRM: 'AzLogin_because_i_dumb'
        commandOptions: '-out main.tfplan'
      displayName: 'Terraform plan'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
        environmentServiceNameAzureRM: 'AzLogin_because_i_dumb'
        commandOptions: 'main.tfplan'
      displayName: 'Terraform apply'
      
#    - task: TerraformTaskV4@4
#      inputs:
#       workingDirectory: '$(System.DefaultWorkingDirectory)/IaC/'
#        provider: 'azurerm'
#        command: 'destroy'
#        environmentServiceNameAzureRM: 'AzLogin_because_i_dumb'

    - script: cp ~/.kube/config $(Build.ArtifactStagingDirectory)/kubeconfig
      displayName: 'Copy kubeconfig to artifacts'
