apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nssfm-demo-ingress
spec:
  rules:
    - host: demo1.skaylink.dev
      http:
        paths:
          - path: /api/v1/nos
            pathType: Prefix
            backend:
              service:
                name: nodejsdemo-service
                port:
                  number: 80
    - host: demo1.skaylink.dev
      http:
        paths:
          - path: /api/v2/son
            pathType: Prefix
            backend:
              service:
                name: nodejsdemo-service2
                port:
                  number: 80



