apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nssfm-demo-ingress
spec:
  rules:
    - host: demo1.skaylink.dev
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: nodejsdemo-service
                port:
                  number: 80
            nginx.ingress.kubernetes.io/rewrite-target: /
          - path: /service2
            pathType: Prefix
            backend:
              service:
                name: nodejsdemo-service2
                port:
                  number: 80
            nginx.ingress.kubernetes.io/rewrite-target: /






