apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsdemo
  template:
    metadata:
      labels:
        app: nodejsdemo
    spec:
      containers:
        - name: nssfmdemo 
          image: nssfm/nssfmdemo:try
          ports:
          - containerPort: 80
