apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: ingress-nginx

