apiVersion: v1
kind: Service
metadata:
  name: nodejsdemo-service
spec:
  selector:
    app: nodejsdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  selector:
    app: nodejsdemo2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer



